# Largely built from this excellent guide:
# https://shift.click/blog/github-actions-rust/#run-on-pushes-to-main--prs-to-main-or-dev

name: Test

env:
  RUST_BACKTRACE: 1

on:
  push:
    branches:
      - master
      - v1
      - 125-windows-support
  pull_request:
    branches:
      - master
      - v1

jobs:
  test:
    name: ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - { rust: stable, os: windows-latest }
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v1

      - if: runner.os == 'Windows'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"

      - if: runner.os == 'Windows'
        run: echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV

      - run: ./scripts/ci.sh "${{ matrix.rust }}" "${{ matrix.os }}"
        shell: bash
